server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: http://10.10.171.145/elevatorOperation/elevator-frontend-backend.git
          search-paths:
            - config-client
          username: username
          password: password
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
